### ISSUE TITLE
Why mycode not running well after implementation

### ISSUE THREAD

**Issue by irwanayeah** [martin-ger/lwip_nat_arduino#5]
why WiFi.hostByName not running well after implementation

code before implement
> code 
> IPAddress ip;
> WiFi.hostByName("google.com", ip);
> Serial.printf("*hostByName google.com     ...%s\n", ip.toString().c_str());

> output
> *hostByName google.com     ...216.58.216.110

output after implement
> output
> *hostByName google.com     ...(IP unset)

any idea?

**Comment by irwanayeah** [comment]
sorry, I have done

**Comment by JayantBenjamin** [comment]
Can you tell me how to install "make" ?
Another error I'm getting is "Multiple Libraries Found "
